name: Deploy_diabetes_to_dockerhub

on:
  push:
    branches:
      - dev

jobs:
  build_docker_image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t raqueelmora/deploy-diabetes:latest .

      - name: Push Docker image to Docker Hub
        run: docker push raqueelmora/deploy-diabetes:latest
